### ISSUE TITLE
Opção mover mudou as permissões de todos os arquivos.

### ISSUE THREAD

**Issue by ramiroluz** [marcosjoao37/Ogarq#3]
Forneci o nome do diretório, cliquei no botão ok sem
escolher uma opção.

Foi exibida uma mensagem: OPÇÃO INVÁLIDA

Cliquei na opção Mover. Foi exibida uma mensagem:
DIRETÓRIO ENCONTRADO! Cliquei em OK.

Foi exibida uma mensagem: Aguarde! Cliquei em OK.

Foi exibida uma mensagem: Tudo pronto e organizado.

Ao rodar ls -l todos os arquivos estavam com
permissão rwxrwxrwx.

As permissões dos arquivos não deveriam ser alteradas.

**Comment by marcosjoao37** [comment]
Resolvido. Entrando no git daqui uns minutos. Obrigado.
