### ISSUE TITLE
Tratar mais extensões.

### ISSUE THREAD

**Issue by ramiroluz** [marcosjoao37/Ogarq#4]
As seguintes extensões não foram tratadas:
asf, bz2, c, cdr, com, csv, dbf, deb, ffm, gz, jigdo
js, lic, log, mim, odg, odp, ods, ogg, ott, part, pdf
phps, pps, ppt, pyc, rtf, sig, stw, svg, swf, sxw, tbz2
tex, tgz, ttf, wma, WMV, xls, xlsx, ZIP

**Comment by marcosjoao37** [comment]
Sim, sim. Adicionarei elas em breve. Obrigado pelo debbuge!

**Comment by ramiroluz** [comment]
Legal, se tiver dúvida quanto à alguma das extensões pode perguntar.

On Tue, Jan 27, 2015 at 2:25 PM, João Marcos Silva e Araújo <
notifications@github.com> wrote:

> Sim, sim. Adicionarei elas em breve. Obrigado pelo debbuge!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcosjoao37/Ogarq/issues/4#issuecomment-71677358.

## 

## 

-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br

**Comment by marcosjoao37** [comment]
Por favor, você poderia listar essas extensões por tipo de arquivo? Gostaria de adiconá-los a biblioteca do programa. Ex: Vídeos: WMV; Compactados: ZIP, tbz2...

**Comment by ramiroluz** [comment]
Olá Marcos.

Eu criei um dicionário com as extensões e os tipos. Adicionei novas pastas.

Acontece que eu li o código e eu acho que seria necessário refatorar. Tem muito código repetido que poderia ser transformado em função.

Além disso se você trabalhar com um dicionário, semelhante ao que eu estou passando, facilita a adição de novas extensões e pastas.

Por exemplo, você pode recuperar um nome de pasta pela extensão e passar como parâmetro para uma função que vai tratar de mover o arquivo para a pasta adequada.

Tem uns dois tipos de arquivo que não sabia para onde mandar, então deixei como Desconhecido.

Se precisar de dicas para melhorar o código podemos fazer juntos aos poucos, marcamos um horário e vamos trabalhando juntos via hangout e editor de código on-line.

{'dbf': 'DB', 'ogg': 'Músicas', 'tex': 'Documentos', 'WMV': 'Vídeos', 'ppt': 'Documentos', 'com': 'Documentos', 'phps': 'Scripts', 'jigdo': 'DwldTool', 'lic': 'Texto', 'ZIP': 'Compactados', 'cdr': 'Figuras', 'stw': 'Documentos', 'xlsx': 'Planilhas', 'wma': 'Músicas', 'xls': 'Planilhas', 'csv': 'Planilhas', 'ott': 'Documentos', 'odg': 'Figuras', 'ttf': 'TTFontes', 'ffm': 'Desconhecido', 'mim': 'Desconhecido', 'c': 'Scripts', 'sxw': 'Documentos', 'tgz': 'Compactados', 'js': 'Scripts', 'pdf': 'Documentos', 'ods': 'Documentos', 'pps': 'Documentos', 'log': 'Texto', 'pyc': 'Scripts', 'gz': 'Compactados', 'swf': 'Vídeos', 'svg': 'Figuras', 'rtf': 'Documentos', 'odp': 'Documentos', 'asf': 'Vídeos', 'sig': 'Assinatura', 'deb': 'Pacotes', 'tbz2': 'Compactados', 'part': 'DwldTool', 'bz2': 'Compactados'}

**Comment by marcosjoao37** [comment]
Obrigado. Vou ver alguns código e tentar refatorar o código, dividí-los em mais classes, em outros arquivos e em pastas diferentes. Quanto ao uso de Dicionários como armazenamento dos tipos de arquivo, achei uma ótima ideia, posso até implementar mais tarde em BD ou colocar para escolher quais arquivos deseja-se "não copiar" ou "quais tipos de arquivo copiar" na própria interface, em um botão opções. Também irei implementar para abrir um navegador do próprio sistema pra escolher a pasta, para melhorar e facilitar o uso. Talvez faça tudo nesta ordem que eu disse.

Só não sei quando vou começar, mas talvez já neste final de semana ou amanhã. Tenho (quase) certeza que precisarei de ajuda. Qualquer coisa te contato - provavelmente - por e-mail.

Obrigado pela ajuda. Está sendo muito bom estas ajuda (e o próprio projeto) pois fixo a ideia de OO tanto em Java (que estudo no colégio) quanto em Python. Mais uma vez, muito obrigado pela ajuda.

**Comment by BernardoGO** [comment]
@ramiroluz, 

Fiz um pull request com um dicionário parecido com o que você disse, apenas  evitei as repetições nos nomes das pastas.

**Comment by marcosjoao37** [comment]
@BernardoGO ,
Ficou bem interessante o uso dos dicionários, contudo, o código ficou um pouquinho bagunçado, mesmo assim consegui entender a lógica. Só não vou aceitar o teu pull pois ficou com várias brechas de erro, como na função Copiar, que ainda está escrita na maneira que eu tinha feito com listas. Ainda vou consertar aquelas funções que estão passando 9 parâmetros de uma só vez, vou tentar simplificá-las. Mesmo assim, obrigado. Usarei a lógica de dicionário para implementar o código, porém, um pouco diferente da que você fez (deixar mais organizado, entende?). Mas muito obrigado, tava precisando dessa ideia.

**Comment by BernardoGO** [comment]
@marcosjoao37 ,

Acho que você olhou a função copiar errada, eu refiz elas.

**Comment by marcosjoao37** [comment]
@BernardoGO ,
Sim, acabei de ver. Vou estudar o que tu fez hoje de madrugada ou amanhã (estou sem tempo pra isso agora, e se for ler, vou acabar lendo algo errado e não vou conseguir entender). Provavelmente vou incorporar. Quando eu ver direitinho, volto a falar contigo. Diminuiu bastante o código - pelo visto. Obrigado!

**Comment by BernardoGO** [comment]
@marcosjoao37,

Eu entendo a confusão, o GitHub mostra o histórico completo e fica parecendo que não foi modificado nas primeiras páginas.
O principal ali foi diminuir repetição e quantidade de código. Veja que para adicionar uma nova pasta basta alterar o dicionario, as funções são genéricas.

**Comment by yakamura** [comment]
@BernardoGO e @marcosjoao37 
vai ter mais coisa adicionada?

**Comment by marcosjoao37** [comment]
@yakamura , como o quê?
