### ISSUE TITLE
Script OgarqSetup.sh não funcionou

### ISSUE THREAD

**Issue by ramiroluz** [marcosjoao37/Ogarq#5]
Rodei o script com o shell padrão bash usando o seguinte comando:

$ . ~/python/Ogarq/OgarqSetup.sh

Foi exibida uma janela do sistema avisando que permissões foram 
concedidas sem pedir senha (configuração do meu sistema) e então
não foi exibida a janela de interface.

**Comment by marcosjoao37** [comment]
Ok. Tentarei limpar o programa para que não precise usar o GKsudo. Obrigado pela ajuda.
