### ISSUE TITLE
Não usar o gksu.

### ISSUE THREAD

**Issue by ramiroluz** [marcosjoao37/Ogarq#6]
Não há necessidade de usar o gksu.
O usuário que quiser usar gksu pode rodar o script OgarqSetup.sh
usando o gksu:

$ gksu ~/python/Ogarq/OgarqSetup.sh

**Comment by marcosjoao37** [comment]
Estava usando o GKsudo para dar permissões para mover os arquivos. Não estava conseguindo sem ele. Vou tentar solucionar o programa e deixá-lo mais limpo.

**Comment by ramiroluz** [comment]
Eu acredito que você não precisa se preocupar com permissões,
se o usuário estiver organizando um diretório que ele já é dono.

Se for um diretório que o usuário não tem permissão, ele pode rodar
o script usando o gksu por conta própria.

On Tue, Jan 27, 2015 at 2:28 PM, João Marcos Silva e Araújo <
notifications@github.com> wrote:

> Estava usando o GKsudo para dar permissões para mover os arquivos. Não
> estava conseguindo sem ele. Vou tentar solucionar o programa e deixá-lo
> mais limpo.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcosjoao37/Ogarq/issues/6#issuecomment-71677847.

## 

## 

-- Ramiro Batista da Luz
-- (41) 9173-2231
-- http://www.ramiroluz.eti.br

**Comment by marcosjoao37** [comment]
Sim, fiz alguns testes e verifiquei isso. Entrando no git daqui uns minutos.
